#!/usr/bin/env python3

########################################################
#                                                      #
#                                                      #
# Script Name : checkfs                                #
# Author      : Nijesh V N                             #
# Use         : Checks the files syste errors on       #
#               different partitions                   #
# Depolyed on : 28th July 2020                         #
#                                                      #
#                                                      #
########################################################

import psutil
import subprocess

partitions = psutil.disk_partitions()

for partition in partitions:
  mpoint = partition.mountpoint
  dev = partition.device

  if mpoint == "/" or mpoint == "/vz":
    proc = subprocess.run(['tune2fs -l {} | grep state'.format(dev)], stdout=subprocess.PIPE, shell=True)
    print('{:10} -    {:5} - {}'.format(dev,mpoint,proc.stdout.decode().split()[-1]))
